#!/usr/bin/env python3
"""Create Utopia of Eternity universe + 5 places via Roblox Open Cloud / universes API.

Requires env:
  ROBLOX_OPEN_CLOUD_API_KEY — API key with universe-places:write (and universe create scope)

Usage:
  export ROBLOX_OPEN_CLOUD_API_KEY=...
  python3 scripts/roblox-create-universe-places.py
  python3 scripts/roblox-create-universe-places.py --universe-id EXISTING  # add places only

Writes PlaceSecrets.luau + prints CatalogSecrets reminder.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLACE_SECRETS = ROOT / "src/ServerScriptService/Secrets/PlaceSecrets.luau"
TEMPLATE_PLACE_ID = 95206881  # Roblox baseplate template (common default)

PLACES = [
    ("Hub", "Utopia Plaza Hub"),
    ("Solhaven", "Solhaven"),
    ("Nocturne", "Nocturne Alley"),
    ("EternityCity", "Utopia of Eternity"),
    ("DeathValley", "Death Valley"),
]


def api_request(
    method: str,
    url: str,
    api_key: str,
    body: dict | None = None,
) -> dict:
    data = json.dumps(body).encode("utf-8") if body is not None else None
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Content-Type": "application/json",
            "x-api-key": api_key,
        },
        method=method,
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            raw = resp.read().decode("utf-8")
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {exc.code} {url}: {detail[:500]}") from exc


def create_universe(api_key: str, name: str) -> int:
    payload = {
        "templatePlaceId": TEMPLATE_PLACE_ID,
        "universeName": name,
    }
    result = api_request(
        "POST",
        "https://apis.roblox.com/universes/v1/universes/create",
        api_key,
        payload,
    )
    universe_id = result.get("universeId") or result.get("id")
    if not universe_id:
        raise RuntimeError(f"Unexpected create universe response: {result}")
    return int(universe_id)


def create_place(api_key: str, universe_id: int, display_name: str) -> int:
    result = api_request(
        "POST",
        f"https://apis.roblox.com/universes/v1/user/universes/{universe_id}/places",
        api_key,
        {"templatePlaceId": TEMPLATE_PLACE_ID, "placeName": display_name},
    )
    place_id = result.get("placeId") or result.get("id")
    if not place_id:
        raise RuntimeError(f"Unexpected create place response: {result}")
    return int(place_id)


def write_place_secrets(universe_id: int, place_map: dict[str, int]) -> None:
    lines = [
        "--!strict",
        "-- AUTO-GENERATED by scripts/roblox-create-universe-places.py",
        "-- See docs/P0-PUBLISH-SETUP.md",
        "return {",
        f"\tUniverseId = {universe_id},",
        "\tCreatorGroupId = 0,",
        "",
    ]
    for key, _name in PLACES:
        pid = place_map.get(key, 0)
        lines.append(f"\t{key} = {pid},")
    lines.append("}")
    lines.append("")
    PLACE_SECRETS.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {PLACE_SECRETS}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Create Roblox universe + 5 places")
    parser.add_argument("--universe-id", type=int, default=0, help="Use existing universe; skip create")
    parser.add_argument("--universe-name", default="Utopia of Eternity", help="Name for new universe")
    args = parser.parse_args()

    api_key = os.getenv("ROBLOX_OPEN_CLOUD_API_KEY", "").strip()
    if not api_key:
        print("ERROR: Set ROBLOX_OPEN_CLOUD_API_KEY", file=sys.stderr)
        return 1

    universe_id = args.universe_id
    if universe_id <= 0:
        print(f"Creating universe: {args.universe_name} ...")
        universe_id = create_universe(api_key, args.universe_name)
        print(f"UniverseId = {universe_id}")

    place_map: dict[str, int] = {}
    for key, display_name in PLACES:
        print(f"Creating place {key} ({display_name}) ...")
        place_id = create_place(api_key, universe_id, display_name)
        place_map[key] = place_id
        print(f"  {key} = {place_id}")

    write_place_secrets(universe_id, place_map)
    print("\nNext: register Developer Products in Dashboard → fill CatalogSecrets.luau")
    print("Validate: python3 scripts/validate-p0-publish.py")
    return 0


if __name__ == "__main__":
    sys.exit(main())
